name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 只有在推送到 main 分支时触发
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # 在仓库设置中添加的 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 在仓库设置中添加的 Docker Hub 密码

      # Step 3: 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/stockdog-web:${{ github.sha }} .

      # Step 4: 推送 Docker 镜像到 Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stockdog-web:${{ github.sha }}
